### ISSUE TITLE
Which versions of Ofx, OfxCV and OfxFacetracker do I need to compile?

### ISSUE THREAD

**Issue by jBachalo** [arturoc/FaceSubstitution#29]
Getting lots of compile errors running the latest versions of Ofx, OfxCV and OfxFaceTracker. Does anyone know which versions I need in order to compile FaceSubstitution and other examples?

Another issue is if I need an older version of OSX SDK. El Capitan it seems only works with XCode 7

**Comment by kylemcdonald** [comment]
ofxCv and ofxFaceTracker are up to date with 0.9.0 but this repo is not maintained. if you want to get it running you have two options:

1. use OF 0.9.0, create a new project file with the project generator, and fix any bugs that have been introduced with API changes in 0.9.0.
2. use a version of OF, ofxCv, and ofxFaceTracker that were all released/updated at the same time.

**Comment by jBachalo** [comment]
Thanks. Option 2 I don't think is an option any more with El Capitan. So will go with option 1.

One question  using the new Project Generator
In this case all of the FaceSubstituion examples have existing Xcode project files.

Should I use the new 'import' feature in Project generator or create new 'blank' project containing the necessary addons and then copy -overwrite the src files over?

**Comment by kylemcdonald** [comment]
sounds like you figured it out. as i said on twitter: ambient light is good. avoid shadows, frontal faces, match the resolution of your camera. just experiment :)
